### ISSUE TITLE
SHX8600 写频软件 v2.0

### ISSUE THREAD

**Issue by scyrte** [SydneyOwl/senhaix-freq-writer-enhanced#15]
设        备：森海克斯 8600
硬件版本：1.0
软件版本：0.14
写频软件 ：2.0

新款森海克斯 8600带对频功能，发射功率由高、低两档，变成高、中、低三档，商家说高=8W，中=5W

大佬能否适配一下这个新版本的机器？

[SHX8600 写频软件 v2.0(中文版).zip](https://github.com/SydneyOwl/senhaix-freq-writer-enhanced/files/15441449/SHX8600.v2.0.zip)

**Comment by SydneyOwl** [comment]
@scyrte 
您好！
在官网上好像没有看到有推出新的机器，这个版本的8600是和旧版8600硬件上有差别是吗？还是硬件相同，只是新固件配套的新写频软件？
另外如果可以的话，麻烦您试试看能否用v0.3.0-beta4为这个新版本的8600读写频（记得先用原软件备份下）~

**Comment by SydneyOwl** [comment]
感谢您的反馈！
精度过高问题已在 #13 中解决，将在下个release中修正！
部分功能、选项缺失或与实际不符问题，之后我再修改修改！

**Comment by SydneyOwl** [comment]
@scyrte 
您提供的写频软件和旧版的写频软件似乎没有太大区别，只是发射功率变为了“高 中 低“三个选项，已在新版本中添加。
您可以下载这个自动编译的新版本，看看是否符合需求：https://github.com/SydneyOwl/senhaix-freq-writer-enhanced/actions/runs/9244123272/artifacts/1538798516

相关变更：https://github.com/SydneyOwl/senhaix-freq-writer-enhanced/commit/cb750d6c0546a44fe6a4b00589473e30d1bffd57

**Comment by SydneyOwl** [comment]
新版本修复了发射功率读写错误的问题，同时取消了信道名称长度的限制。
在新版8600写频软件上未发现有`发射结束提示音`这一功能，请问在软件中修改这一选项手台是否会同步更改？
可在此处下载最新编译产物：https://github.com/SydneyOwl/senhaix-freq-writer-enhanced/actions/runs/9246756188/artifacts/1539196910

**Comment by SydneyOwl** [comment]
@scyrte 这两个问题可能是固件的问题，用8800试了一下，发射允许选NO的话确实不可发射

**Comment by SydneyOwl** [comment]
想问下使用原版软件也存在“某个信道发射允许选NO手台还是可以发射”这样的问题吗？

**Comment by SydneyOwl** [comment]
那应该就是固件的问题了

**Comment by SydneyOwl** [comment]
已在v0.3.0中解决了上述问题，该issue将被关闭。  感谢支持~
