### ISSUE TITLE
建议打星助手增加手动输入频率的功能

### ISSUE THREAD

**Issue by YX-CT** [SydneyOwl/senhaix-freq-writer-enhanced#16]
非常感谢大佬开发的打星助手！目前的星历很全，但是有些卫星的频率是一个范围或者几个可选频率，这种情况下是不支持直接插入的。是否有可能在下方多普勒的差频旁边增加一个自定义上下行频率的选项，然后利用软件自动计算多普勒后插入？

**Comment by SydneyOwl** [comment]
感谢您的建议！新版本中将加入该功能~

**Comment by SydneyOwl** [comment]
已加入该功能！
新版本还未发布，可在此处下载编译产物：https://github.com/SydneyOwl/senhaix-freq-writer-enhanced/actions/runs/9382577639/artifacts/1570560027

**Comment by YX-CT** [comment]
> 已加入该功能！ 新版本还未发布，可在此处下载编译产物：https://github.com/SydneyOwl/senhaix-freq-writer-enhanced/actions/runs/9382577639/artifacts/1570560027

感谢大佬，您考虑的太周到了，超级好用！！！
