### ISSUE TITLE
0.3.0和0.3.1保存的数据不互通

### ISSUE THREAD

**Issue by YX-CT** [SydneyOwl/senhaix-freq-writer-enhanced#17]
大佬您好，由于需要去找之前导出的数据，我发现0.3.0和0.3.1保存出来的数据不能互相导入，请问有可能解决一下吗？不好解决的话我就两个版本交替着用。

**Comment by SydneyOwl** [comment]
您好！
只需要把0.3.0中导出的文件用vscode或其他编辑器打开，把ChannelData改为ChanneldataList再在0.3.1中导入应该就ok了
![image](https://github.com/SydneyOwl/senhaix-freq-writer-enhanced/assets/84191144/17906b51-3443-4bea-88b6-5b594860ab63)
![image](https://github.com/SydneyOwl/senhaix-freq-writer-enhanced/assets/84191144/6d0db408-2c5d-4726-9e81-5693fce9a6aa)

**Comment by YX-CT** [comment]
> 您好！ 只需要把0.3.0中导出的文件用vscode或其他编辑器打开，把ChannelData改为ChanneldataList再在0.3.1中导入应该就ok了 ![image](https://private-user-images.githubusercontent.com/84191144/338422825-17906b51-3443-4bea-88b6-5b594860ab63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODMwNTcsIm5iZiI6MTcxODA4Mjc1NywicGF0aCI6Ii84NDE5MTE0NC8zMzg0MjI4MjUtMTc5MDZiNTEtMzQ0My00YmVhLTg4YjYtNWI1OTQ4NjBhYjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA1MTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NWIwZTg4N2JmMzJiMzg3YjdiNzE4NzI2NjQ3YWM4NjVlMGVkYjZhMWVhMDY5MTFmZGRjNjk0ZGZhODExZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WBf7InlQIGK83fGWdu8jVlb_Yk6oC3KXYby0yEJJTxY) ![image](https://private-user-images.githubusercontent.com/84191144/338423018-6d0db408-2c5d-4726-9e81-5693fce9a6aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODMwNTcsIm5iZiI6MTcxODA4Mjc1NywicGF0aCI6Ii84NDE5MTE0NC8zMzg0MjMwMTgtNmQwZGI0MDgtMmM1ZC00NzI2LTllODEtNTY5M2ZjZTlhNmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA1MTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YThkNTU3NDA1ODg3OWUyNDI5NmIxYzQxYmFiN2JkNmY2ZGE1YjQxZDk3YTE4YTFhOWJlMzY0YWMyNzUxNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0cFTIPRVB8eFN4YlclPjL3QRl4TRzpPQ6zytTMNGWeM)

好嘞，谢谢您！！
