### ISSUE TITLE
有没有人遇到过编辑内容的时候程序卡死并崩溃的情况？| Anybody met stuck and crushing of the software while editing contents?

### ISSUE THREAD

**Issue by BH2WFR** [SydneyOwl/senhaix-freq-writer-enhanced#18]
Environment:
OS: Windows 11 23H2 (x64)

**Comment by SydneyOwl** [comment]
是在编辑什么内容时闪退的呢？
如果有git bash的话，能否从那里打开软件，并复现一下闪退，把输出的日志复制给我下？
![image](https://github.com/user-attachments/assets/08f79fcd-54ad-4e7a-a350-539053eb7035)

**Comment by RikkaNaa** [comment]
试了一下编辑完发射频率直接点亚音编码的话就会卡死，在 Linux 和 Windows 下均可复现

**Comment by BH2WFR** [comment]
> 试了一下编辑完发射频率直接点亚音编码的话就会卡死，过一会就闪退，在 Linux 和 Windows 下均可复现 部分 log：https://justpaste.it/a8vcj 因为太长了被终端截掉了上面一部分

是的, 好像我记得崩溃的时候刚刚改完亚音, 收回下拉框以后, 再拖动列表顺序, 就崩溃了

**Comment by SydneyOwl** [comment]
@RikkaNaa @BH2WFR 
问题已复现，经排查应该是升级后的avalonia新引进的bug，已将其降级至`11.0.11`。
您可以在release中下载修正后的版本`v0.4.1`，如果bug仍然存在烦请告知~
